package com.cse3310;

import java.utils.ArrayList;


public class Game
{
    private ArrayList User users;

    public boolean checkVertical(array selectedLetters, int length)
    {
        return true;
    }

    public boolean checkDiagonal(array selectedLetters, int length)
    {
        return true;
    }

    public boolean checkHorizontal(array selectedLetters, int length)
    {

    }

    public void checkWin(User user)
    {

    }

    public String keepScore(array)
}